version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - run:
          command: apt-get update && apt-get install make
      - run:
          command: make clean check
